### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.qiniu.droid.rtc.demo.utils.UpdateApkFileProvider: 

### ISSUE THREAD

**Issue by ShiverZm** [pili-engineering/QNRTC-Android#30]
当我clone完并调整项目配置结束之后，开始运行 demo无法运行且报错
java.lang.RuntimeException: Unable to get provider com.qiniu.droid.rtc.demo.utils.UpdateApkFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5898)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5806)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:608)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:392)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6384)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5898) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5806) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6649) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by kvlee** [comment]
这个错误是 7.0 文件系统权限导致的， 请设置下 fileprovider 配饰 path
