### ISSUE TITLE
初始化就提示失败

### ISSUE THREAD

**Issue by fanxiang132** [pili-engineering/QNRTC-Android#55]
![image](https://user-images.githubusercontent.com/20007793/102185547-280bd480-3eec-11eb-9b19-c49cbecb12c3.png)
调用： QNRTCEnv.init(getApplicationContext());
  java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)

**Comment by OurEra** [comment]
清理下IDE cache试下？

**Comment by fanxiang132** [comment]
运行的时候报这些这些错误









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pili-engineering/QNRTC-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 下午4:32
收件人:&nbsp;"pili-engineering/QNRTC-Android"<QNRTC-Android@noreply.github.com&gt;;
抄送:&nbsp;"Eric"<921495007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pili-engineering/QNRTC-Android] 初始化就提示失败 (#55)





 
清理下IDE cache试下？

**Comment by OurEra** [comment]
请确认编译有带上
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
还有有问题，可以提交完整日志文件

**Comment by fanxiang132** [comment]
是否需要把android studio改成java和kotlin混合？
加上后报下面的错误





&gt; Task :app:compileDebugJavaWithJavac
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
&gt; Task :app:compileDebugNdk NO-SOURCE
&gt; Task :app:compileDebugSources
&gt; Task :app:mergeDebugShaders
&gt; Task :app:compileDebugShaders
&gt; Task :app:generateDebugAssets
&gt; Task :dotnetcoresignalrclientjava:mergeDebugShaders
&gt; Task :dotnetcoresignalrclientjava:compileDebugShaders
&gt; Task :dotnetcoresignalrclientjava:generateDebugAssets
&gt; Task :dotnetcoresignalrclientjava:packageDebugAssets
&gt; Task :app:mergeDebugAssets
error processing C:\Users\fanx\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.4.10\30e46450b0bb3dbf43898d2f461be4a942784780\kotlin-stdlib-jdk7-1.4.10.jar
java.lang.RuntimeException
&nbsp;at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
&nbsp;at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
&nbsp;at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
&nbsp;at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
&nbsp;at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
&nbsp;at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
&nbsp;at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
error processing C:\Users\fanx\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.4.10\ea29e063d2bbe695be13e9d044dcfb0c7add398e\kotlin-stdlib-1.4.10.jar
java.lang.RuntimeException
&nbsp;at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
&nbsp;at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
&nbsp;at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
&nbsp;at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
&nbsp;at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
&nbsp;at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
&nbsp;at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
error processing C:\Users\fanx\.gradle\caches\transforms-2\files-2.1\63a656166ce979988e33b4ecb73dd643\jetified-gson-2.8.6.jar
java.lang.RuntimeException
&nbsp;at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
&nbsp;at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
&nbsp;at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
&nbsp;at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
&nbsp;at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
&nbsp;at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
&nbsp;at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
error processing C:\Users\fanx\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.64\1467dac1b787b5ad2a18201c0c281df69882259e\bcprov-jdk15on-1.64.jar
java.lang.RuntimeException
&nbsp;at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
&nbsp;at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
&nbsp;at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
&nbsp;at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
&nbsp;at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
&nbsp;at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
&nbsp;at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
&gt; Task :app:transformClassesWithDexBuilderForDebug FAILED
java.lang.RuntimeException: java.lang.RuntimeException
&nbsp;at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
&nbsp;at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
&nbsp;at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
&nbsp;at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
&nbsp;at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
&nbsp;at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
&nbsp;at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
&nbsp;at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getInitalGraphData(DesugarIncrementalTransformHelper.java:162)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.makeDesugaringGraph(DesugarIncrementalTransformHelper.java:130)
&nbsp;at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getDependenciesPaths(DesugarIncrementalTransformHelper.java:231)
&nbsp;at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.getD8DesugaringCacheInfo(DexArchiveBuilderTransform.java:461)
&nbsp;at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:375)
&nbsp;at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
&nbsp;at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
&nbsp;at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
&nbsp;at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
&nbsp;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
&nbsp;at java.lang.reflect.Method.invoke(Method.java:498)
&nbsp;at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
&nbsp;at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
&nbsp;at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
&nbsp;at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
&nbsp;at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
&nbsp;at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
&nbsp;at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
&nbsp;at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
&nbsp;at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
&nbsp;at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
&nbsp;at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
&nbsp;at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
&nbsp;at java.util.Optional.map(Optional.java:215)
&nbsp;at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
&nbsp;at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
&nbsp;at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
&nbsp;at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
&nbsp;at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
&nbsp;at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
&nbsp;at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
&nbsp;at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
&nbsp;at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
&nbsp;at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
&nbsp;at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
&nbsp;at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
&nbsp;at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
&nbsp;at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
&nbsp;at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
&nbsp;at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
&nbsp;at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
&nbsp;at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
&nbsp;at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
&nbsp;at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
&nbsp;at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
&nbsp;at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
&nbsp;at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
&nbsp;at java.util.Optional.map(Optional.java:215)
&nbsp;at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
&nbsp;at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
&nbsp;at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
&nbsp;at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
&nbsp;at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
&nbsp;at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
&nbsp;at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
&nbsp;at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
&nbsp;at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
&nbsp;at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
&nbsp;at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
&nbsp;at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
&nbsp;at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
&nbsp;at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
&nbsp;at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
&nbsp;at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
&nbsp;at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
&nbsp;at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
&nbsp;at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
&nbsp;at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
&nbsp;at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
&nbsp;at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
&nbsp;at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
&nbsp;at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
&nbsp;at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
&nbsp;at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
&nbsp;at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
&nbsp;at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
&nbsp;at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
&nbsp;at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
&nbsp;at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
&nbsp;at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
&nbsp;at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
&nbsp;at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
&nbsp;at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
&nbsp;at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
&nbsp;at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
&nbsp;at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
&nbsp;at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
&nbsp;at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
&nbsp;at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
&nbsp;at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
&nbsp;at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
&nbsp;at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
&nbsp;at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
&nbsp;at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
&nbsp;at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
&nbsp;at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
&nbsp;at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
&nbsp;at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
&nbsp;at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
&nbsp;at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
&nbsp;at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
&nbsp;at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
&gt; com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 30s
37 actionable tasks: 34 executed, 3 up-to-date




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pili-engineering/QNRTC-Android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 下午5:33
收件人:&nbsp;"pili-engineering/QNRTC-Android"<QNRTC-Android@noreply.github.com&gt;;
抄送:&nbsp;"Eric"<921495007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pili-engineering/QNRTC-Android] 初始化就提示失败 (#55)





 
请确认编译有带上
 compileOptions {
 sourceCompatibility JavaVersion.VERSION_1_8
 targetCompatibility JavaVersion.VERSION_1_8
 }
 还有有问题，可以提交完整日志文件
